#Step 1: Build stage
FROM node:14.16.0-alpine3.13 AS build-stage
RUN npm install -g @angular/cli@10.1.7
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN ng build --prod
# RUN ng build --prod --base-href /performa/

#Step 2: Production
FROM nginx:1.23.3-alpine
# ENV API_URL=https://performa-api.rem-si.com
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ] 